---
rvm:
  - "2.0.0"
  - "1.9.3"
  - "1.9.2"
  - jruby-19mode
  - rbx-19mode

env:
  - DB=sqlite DATABASE="sqlite://coinpunk-test.sqlite3" JDBC_DATABASE="jdbc:sqlite://coinpunk-test.sqlite3"
  - DB=mysql2 DATABASE="mysql2://root@127.0.0.1/coinpunk_test" JDBC_DATABASE="jdbc:mysql://127.0.0.1/coinpunk_test"
  - DB=postgres DATABASE="postgres://postgres@127.0.0.1/coinpunk_test" JDBC_DATABASE="jdbc:postgresql://postgres@127.0.0.1/coinpunk_test"

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS coinpunk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database coinpunk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'create database IF NOT EXISTS coinpunk_test'; fi"
  - "bundle exec rake db:bootstrap RACK_ENV=test"
